### ISSUE TITLE
Default Illumina quality scores are too low

### ISSUE THREAD

**Issue by niemasd** [nh13/DWGSIM#43]
I simulated a dataset using the default settings for Illumina paired-end and ran it through FastQC, and the range of quality scores are all in the red:

![FastQC summary](http://i.imgur.com/BnUEcnp.png)

EDIT: It also could simply be a matter of outdated quality score encoding, not sure (I'm not too familiar with sequencing technologies)

**Comment by nh13** [comment]
If you aren't using the `-q` option to for a fixed quality, then it is governed by the per-base error rate (see `-e` and `-E`) which are set to a fixed value by default to `0.02`, which is `16.9897` (`= log10(0.02) * -10`).  The standard deviation for quality scores is set by `-Q`, which by default is `2`, so most of the data should be within a two standard deviations, so that's why your seeing a range of `15` to `20`.  Please examine the help message and available options for more information.  You may need to also dive into the source code, but since you are in the Pevnzer lab that shouldn't be a proble ;).

**Comment by niemasd** [comment]
Ah, my apologies! I'm inexperienced with with actual sequence data (I typically only deal with theoretical), but I started guessing it was simply user error as I was googling (hence the edit). My mistake! I'll take a closer look! And thanks again for the quick response!
