### ISSUE TITLE
 DWGSIM is painfully slow for long reads

### ISSUE THREAD

**Issue by snayfach** [nh13/DWGSIM#65]
I'd like to use the tool to generate long read Ion Torrent data. Using this runs fine:
`dwgsim -f TACG -c 2 -B -N 100 test.fna dwgsim-out/test`

However, simulating 10 kb takes forever:
`dwgsim -1 10000 -f TACG -c 2 -B -N 100 test.fna dwgsim-out/test`

Is there any way to quickly generate long read Ion Torrent data?

**Comment by nh13** [comment]
Can you post your fasta?

**Comment by snayfach** [comment]
Please see attached. File was compressed to enable upload
[test.fna.zip](https://github.com/nh13/DWGSIM/files/5777993/test.fna.zip)

**Comment by nh13** [comment]
If you want fragment reads, use `-1 10000 -2 0`. 

If you want paired end/mate pair reads, then you'll want to adjust `-d` to be at least the size of the longest read length.  If you set this to `-d 10000` you'll have most of R1 and R2 overlapping. 

I am curious what you're simulating this for, since Ion Torrent reads cannot be 10Kb in length, and 454 isn't in business.

**Comment by snayfach** [comment]
Sorry, I should have said oxford nanopore reads, not ion torrent. I found a solution using [badread](https://github.com/rrwick/Badread), which was designed for this.
